set_project("eidolonrt")
set_version("0.0.1")
add_repositories("charon " .. (os.getenv("CHARON_REPO") or "https://github.com/kern0x1b/charon.git"))
add_addons("charon latest")
set_config("apple_minimum", "6.0")
includes("@addon/charon/apple-ios")
set_allowedplats("iphoneos")
set_allowedarchs("iphoneos|armv7")
set_defaultplat("iphoneos")
set_defaultarchs("iphoneos|armv7")
add_requires("charon@swift-runtime", {alias = "swift-runtime"})
add_requires("charon@libcxx", {alias = "libcxx"})
add_requires("charon@opencombine", {alias = "opencombine"})

target("eidolonrt")
    add_rules("@addon/charon/daemon", "@addon/charon/swift")
    add_packages("opencombine")
    add_files("main.swift")
    add_frameworks("Foundation", "CoreData")
    set_values("charon.control", "control")
